# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.8
#
# <auto-generated>
#
# Generated from file `MyInterface.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module Example
_M_Example = Ice.openModule('Example')
__name__ = 'Example'

if 'Musique' not in _M_Example.__dict__:
    _M_Example.Musique = Ice.createTempClass()
    class Musique(Ice.Value):
        def __init__(self, nom='', auteur='', type=''):
            self.nom = nom
            self.auteur = auteur
            self.type = type

        def ice_id(self):
            return '::Example::Musique'

        @staticmethod
        def ice_staticId():
            return '::Example::Musique'

        def __str__(self):
            return IcePy.stringify(self, _M_Example._t_Musique)

        __repr__ = __str__

    _M_Example._t_Musique = IcePy.defineValue('::Example::Musique', Musique, -1, (), False, False, None, (
        ('nom', (), IcePy._t_string, False, 0),
        ('auteur', (), IcePy._t_string, False, 0),
        ('type', (), IcePy._t_string, False, 0)
    ))
    Musique._ice_type = _M_Example._t_Musique

    _M_Example.Musique = Musique
    del Musique

if '_t_musiques' not in _M_Example.__dict__:
    _M_Example._t_musiques = IcePy.defineSequence('::Example::musiques', (), IcePy._t_string)

if '_t_test' not in _M_Example.__dict__:
    _M_Example._t_test = IcePy.defineSequence('::Example::test', (), IcePy._t_byte)

_M_Example._t_MyInterface = IcePy.defineValue('::Example::MyInterface', Ice.Value, -1, (), False, True, None, ())

if 'MyInterfacePrx' not in _M_Example.__dict__:
    _M_Example.MyInterfacePrx = Ice.createTempClass()
    class MyInterfacePrx(Ice.ObjectPrx):

        def printMessage(self, message, context=None):
            return _M_Example.MyInterface._op_printMessage.invoke(self, ((message, ), context))

        def printMessageAsync(self, message, context=None):
            return _M_Example.MyInterface._op_printMessage.invokeAsync(self, ((message, ), context))

        def begin_printMessage(self, message, _response=None, _ex=None, _sent=None, context=None):
            return _M_Example.MyInterface._op_printMessage.begin(self, ((message, ), _response, _ex, _sent, context))

        def end_printMessage(self, _r):
            return _M_Example.MyInterface._op_printMessage.end(self, _r)

        def getMusiques(self, genre, context=None):
            return _M_Example.MyInterface._op_getMusiques.invoke(self, ((genre, ), context))

        def getMusiquesAsync(self, genre, context=None):
            return _M_Example.MyInterface._op_getMusiques.invokeAsync(self, ((genre, ), context))

        def begin_getMusiques(self, genre, _response=None, _ex=None, _sent=None, context=None):
            return _M_Example.MyInterface._op_getMusiques.begin(self, ((genre, ), _response, _ex, _sent, context))

        def end_getMusiques(self, _r):
            return _M_Example.MyInterface._op_getMusiques.end(self, _r)

        def supprimerMusique(self, nom, auteur, context=None):
            return _M_Example.MyInterface._op_supprimerMusique.invoke(self, ((nom, auteur), context))

        def supprimerMusiqueAsync(self, nom, auteur, context=None):
            return _M_Example.MyInterface._op_supprimerMusique.invokeAsync(self, ((nom, auteur), context))

        def begin_supprimerMusique(self, nom, auteur, _response=None, _ex=None, _sent=None, context=None):
            return _M_Example.MyInterface._op_supprimerMusique.begin(self, ((nom, auteur), _response, _ex, _sent, context))

        def end_supprimerMusique(self, _r):
            return _M_Example.MyInterface._op_supprimerMusique.end(self, _r)

        def updateMusique(self, oldNom, nvNom, auteur, context=None):
            return _M_Example.MyInterface._op_updateMusique.invoke(self, ((oldNom, nvNom, auteur), context))

        def updateMusiqueAsync(self, oldNom, nvNom, auteur, context=None):
            return _M_Example.MyInterface._op_updateMusique.invokeAsync(self, ((oldNom, nvNom, auteur), context))

        def begin_updateMusique(self, oldNom, nvNom, auteur, _response=None, _ex=None, _sent=None, context=None):
            return _M_Example.MyInterface._op_updateMusique.begin(self, ((oldNom, nvNom, auteur), _response, _ex, _sent, context))

        def end_updateMusique(self, _r):
            return _M_Example.MyInterface._op_updateMusique.end(self, _r)

        def addMusique(self, genre, nom, auteur, context=None):
            return _M_Example.MyInterface._op_addMusique.invoke(self, ((genre, nom, auteur), context))

        def addMusiqueAsync(self, genre, nom, auteur, context=None):
            return _M_Example.MyInterface._op_addMusique.invokeAsync(self, ((genre, nom, auteur), context))

        def begin_addMusique(self, genre, nom, auteur, _response=None, _ex=None, _sent=None, context=None):
            return _M_Example.MyInterface._op_addMusique.begin(self, ((genre, nom, auteur), _response, _ex, _sent, context))

        def end_addMusique(self, _r):
            return _M_Example.MyInterface._op_addMusique.end(self, _r)

        def getFavoris(self, context=None):
            return _M_Example.MyInterface._op_getFavoris.invoke(self, ((), context))

        def getFavorisAsync(self, context=None):
            return _M_Example.MyInterface._op_getFavoris.invokeAsync(self, ((), context))

        def begin_getFavoris(self, _response=None, _ex=None, _sent=None, context=None):
            return _M_Example.MyInterface._op_getFavoris.begin(self, ((), _response, _ex, _sent, context))

        def end_getFavoris(self, _r):
            return _M_Example.MyInterface._op_getFavoris.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_Example.MyInterfacePrx.ice_checkedCast(proxy, '::Example::MyInterface', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_Example.MyInterfacePrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::Example::MyInterface'
    _M_Example._t_MyInterfacePrx = IcePy.defineProxy('::Example::MyInterface', MyInterfacePrx)

    _M_Example.MyInterfacePrx = MyInterfacePrx
    del MyInterfacePrx

    _M_Example.MyInterface = Ice.createTempClass()
    class MyInterface(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Example::MyInterface', '::Ice::Object')

        def ice_id(self, current=None):
            return '::Example::MyInterface'

        @staticmethod
        def ice_staticId():
            return '::Example::MyInterface'

        def printMessage(self, message, current=None):
            raise NotImplementedError("servant method 'printMessage' not implemented")

        def getMusiques(self, genre, current=None):
            raise NotImplementedError("servant method 'getMusiques' not implemented")

        def supprimerMusique(self, nom, auteur, current=None):
            raise NotImplementedError("servant method 'supprimerMusique' not implemented")

        def updateMusique(self, oldNom, nvNom, auteur, current=None):
            raise NotImplementedError("servant method 'updateMusique' not implemented")

        def addMusique(self, genre, nom, auteur, current=None):
            raise NotImplementedError("servant method 'addMusique' not implemented")

        def getFavoris(self, current=None):
            raise NotImplementedError("servant method 'getFavoris' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_Example._t_MyInterfaceDisp)

        __repr__ = __str__

    _M_Example._t_MyInterfaceDisp = IcePy.defineClass('::Example::MyInterface', MyInterface, (), None, ())
    MyInterface._ice_type = _M_Example._t_MyInterfaceDisp

    MyInterface._op_printMessage = IcePy.Operation('printMessage', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), None, ())
    MyInterface._op_getMusiques = IcePy.Operation('getMusiques', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), ((), _M_Example._t_musiques, False, 0), ())
    MyInterface._op_supprimerMusique = IcePy.Operation('supprimerMusique', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0)), (), ((), IcePy._t_bool, False, 0), ())
    MyInterface._op_updateMusique = IcePy.Operation('updateMusique', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0)), (), ((), IcePy._t_bool, False, 0), ())
    MyInterface._op_addMusique = IcePy.Operation('addMusique', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0), ((), IcePy._t_string, False, 0)), (), ((), _M_Example._t_test, False, 0), ())
    MyInterface._op_getFavoris = IcePy.Operation('getFavoris', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (), ((), _M_Example._t_musiques, False, 0), ())

    _M_Example.MyInterface = MyInterface
    del MyInterface

# End of module Example
